# Install script for directory: C:/ProgramData/NVIDIA Corporation/OptiX SDK 3.7.0/SDK

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/OptiX-Samples")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/ambocc/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/buffersOfBuffers/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/collision/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/cook/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/device_exceptions/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/displacement/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/glass/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/heightfield/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/hybridShadows/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/isgReflections/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/isgShadows/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/julia/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/mantascene/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/materials/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/mcmc_sampler/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/mis_sample/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/namespaces/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/ocean/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/path_tracer/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/primitiveIndexOffsets/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/procedural/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/progressivePhotonMap/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/rayDifferentials/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample1/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample2/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample3/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample4/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample5/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample5pp/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample6/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample7/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sample8/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/shadeTree/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simpleAnimation/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simpleGLTexInterop/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrime/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrimeInstancing/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrimeMasking/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrimepp/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrimeppMultiGpu/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/simplePrimeppMultiBuffering/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/swimmingShark/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/transparency/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/traversal/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/tutorial/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/whirligig/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/whitted/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/zoneplate/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/sutil/cmake_install.cmake")
  include("C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/nvcommon/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/Users/Adrian/Documents/Visual Studio 2013/Projects/OptixSdk/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
